version: 1

workspace:
  project_root: terraform
  terraform_version: 1.9.8
  backend_type: azurerm

stack:
  name: azure-vm-health
  description: "Terraform-managed Azure VM Health Monitoring Environment"

  before_plan:
    - echo "Running Terraform plan"
  
  after_apply:
    - echo "Deployment complete!"
