version: 1

workspace:
  project_root: terraform
  terraform_version: 1.10.6
  backend_type: spacelift

stack:
  name: azure-vm-health
  description: "Terraform-managed Azure VM Health Monitoring Environment"

  before_plan:
    - echo "Running Terraform plan"
  
  after_apply:
    - echo "Deployment complete!"
