resource "azurerm_resource_group" "rg" {}
resource "azurerm_virtual_network" "vnet" {}
resource "azurerm_subnet" "subnet" {}
resource "azurerm_network_security_group" "nsg" {}
resource "azurerm_network_interface" "nic" {}
resource "azurerm_linux_virtual_machine" "vm" {}
resource "azurerm_storage_account" "storage" {}
resource "azurerm_log_analytics_workspace" "logws" {}
resource "azurerm_monitor_metric_alert" "alert" {}
